name: integ testing action
on: [push]
jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' 
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python3 main.py
        env:
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          FINE_TUNED: ${{ secrets.FINE_TUNED }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./hearsay-client
  #   steps:
  #     # - name: Checkout
  #     # - uses: actions/checkout@v2
  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v4.2.0 # use the explicit version number
  #       working-directory: ./hearsay-client
  #       with:
  #         build: npm run build
  #         start: npm start