name: integ testing action
on: [push, pull_request]
jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          install: npm install
          start: npm start
          working-directory: hearsay-client